package dataprovider;

import org.testng.annotations.DataProvider;

public class BreedDataProvider {

    @DataProvider(name = "breeds")
    public static Object[][] breeds() {
        return new Object[][]{
                {"affenpinscher"},
                {"african"},
                {"airedale"},
                {"akita"},
                {"appenzeller"},
                {"basenji"},
                {"beagle"},
                {"bluetick"},
                {"borzoi"},
                {"bouvier"},
                {"boxer"},
                {"brabancon"},
                {"briard"},
                {"cavapoo"},
                {"chihuahua"},
                {"chow"},
                {"clumber"},
                {"cockapoo"},
                {"coonhound"},
                {"cotondetulear"},
                {"dachshund"},
                {"dalmatian"},
                {"dhole"},
                {"dingo"},
                {"doberman"},
                {"entlebucher"},
                {"eskimo"},
                {"germanshepherd"},
                {"groenendael"},
                {"havanese"},
                {"husky"},
                {"keeshond"},
                {"kelpie"},
                {"kombai"},
                {"komondor"},
                {"kuvasz"},
                {"labradoodle"},
                {"labrador"},
                {"leonberg"},
                {"lhasa"},
                {"malamute"},
                {"malinois"},
                {"maltese"},
                {"mexicanhairless"},
                {"mix"},
                {"newfoundland"},
                {"otterhound"},
                {"papillon"},
                {"pekinese"},
                {"pembroke"},
                {"pitbull"},
                {"pomeranian"},
                {"pug"},
                {"puggle"},
                {"pyrenees"},
                {"redbone"},
                {"rottweiler"},
                {"saluki"},
                {"samoyed"},
                {"schipperke"},
                {"sharpei"},
                {"shiba"},
                {"shihtzu"},
                {"stbernard"},
                {"tervuren"},
                {"vizsla"},
                {"weimaraner"},
                {"whippet"}
        };
    }
}
